@startuml

package "Cypherer" {
    package "view" {
        class "Cypherer" {
            -- Attributes --
            - CyphererModel model
            - StringVar keyVar
            - StringVar imgVar
            - StringVar rslVar
            - BooleanVar byVar
            - IntVar progressBarValue
            - list l
            -- Methods --
            - void createModel()
            - void createView()
            - void placeComponents()
            - void createController()
            - void chooseKey()
            - void chooseImg()
            - void chooseRsl()
            - void hasByVarChanged()
            - void decypherer()
            - void cypher()
            - void execute()
            - void generateKey()
            - void reset()
            - void updateKeyCanvas(event)
            - void updateImageCanvas(event)
            - void updateResultCanvas(event)
            - void switchButtonState(state)
            - void updateProgressBarValue(event)
        }
    }
    package "model" {
        class "CyphererModel" {
            -- Attributes --
            - String imagePath
            - String keyPath
            - String resultPath
            - PropertyChangeListenerSupport support
            - ChangeListenerSupport changeSupport
            - ChangeEvent event
            - Lock lock
            -- Properties --
            + String imagePath (R|W)
            + String keyPath (R|W)
            + String resultPath (R|W)
            -- Methods --
            + void cypher()
            + void addChangeListener(changeListener)
            + void removeChangeListener(changeListener)
            + void addPropertyChangeListener(propertyChangeListener)
            + void removePropertyChangeListener(propertyChangeListener)
            - void fireStateChanged()
            - void firePropertyStateChanged(propName)
            - void cypher()
        }
        class "MismatchFormatException"
    }
    class "Initializer" {
        -- Attributes --
        - PluginManager loader
        -- Methods --
        + Cypherer getFrame(master)
        + String getName()
    }
}
hide empty members
center footer Tous les attributs liés à des composants graphiques ne sont pas affichés
title Description du paquetage Cypherer
@enduml