@startuml

package "Generator" {
    package "model" {
        class "GeneratorModel" {
            -- Statics --
            + static list ImagePossibility
            -- Attributes --
            - int height
            - int width
            - Image key
            - PropertyChangeSupport support
            - ChangeSupport changeSupport
            - ChangeEvent event
            - Lock lock
            -- Methods --
            + void generateKey()
            + Image getKey()
            + tuple getSize()
            + void setSize(w, h)
            + void addPropertyChangeListener(propertyChangeListener)
            + void removePropertyChangeListener(propertyChangeListener)
            + void addChangeListener(changeListener)
            + void removeChangeListener(changeListener)
            - void firePropertyStateChange(propName)
            - void fireStateChanged()
            - void generate()
        }
    }
    package "view" {
        class "GeneratorView" {
            -- Attribute --
            - GeneratorModel model
            - BooleanVar byVar
            - IntVar widthVar
            - IntVar heightVar
            - StringVar picturePathVar
            - IntVar progressVar
            -- Methods --
            - void createModel()
            - void createView()
            - void placeComponents()
            - void createController()
            - void hasByVarChanged()
            - void savePicture(event)
            - void validateEntry()
            - void onGenButtonClick()
            - void updateCanvasDisplay()
            - void updateProgressBarValue(event)
            - void onLoadButtonCLick()
        }
    }
    class "Initializer" {
        -- Attributes --
        - PluginManager loader
        -- Methods --
        + GeneratorView getFrame(master)
        + String getName()
    }
}
hide empty members
center footer Tous les attributs liés à des composants graphiques ne sont pas affichés
title Description du paquetage Generator
@enduml