@startuml
package "ImageFormatter" {
    package "model" {
        class "NoImageToConvert"
        class "ImageFormatterModel" {
            -- Attributes --
            - Image origin
            - Image converted
            - Lock lock
            - PropertyChangeSupport support
            -- Properties --
            + originalPicture (R|W)
            + convertedPicture (R)
            -- Methods --
            + void convert()
            + void addPropertyChangeListener(propertyChangeListener)
            + void removePropertyChaneListener(propertyChangeListener)
            - void convertThread()
            - void firePropertyStateChange(propName)
        }
    }
    package "view" {
        class "ImageFormatter" {
            -- Statics --
            + list FORMATS
            -- Attributes --
            - ImageFormatterModel model
            - StringVar originalStrVar
            - StringVar convertedStringVar
            -- Methods --
            - void createModel()
            - void createView()
            - void placeComponents()
            - void createController()
            - void onOriginalButtonClick()
            - void onConvertedButtonClick()
            - void onConvertButtonClick()
        }
    }
    class "Initializer" {
        -- Attributes --
        - PluginManager loader
        -- Methods --
        + ImageFormatter getFrame(master)
        + String getName()
    }
}
hide empty members
center footer Tous les attributs liés à des composants graphiques ne sont pas affichés
title Description du paquetage ImageFormatter
@enduml